framework:
    workflows:
        sutekinabox_publishing:
            type: 'workflow' # or 'state_machine'
            marking_store:
                type: 'single_state' # or 'multiple_state'
                arguments:
                    - 'state'
            supports:
                - App\Entity\SutekinaBox
                - App\SutekinaBox\SutekinaBoxRequest
            initial_place: to_validate
            places:
                - to_validate
                - to_check_stock
                - validated
                - prepatation_allowed
            transitions:
                to_validate:
                    from: to_validate
                    to:   to_check_stock
                to_check:
                    from: to_check_stock
                    to:   validated
                validate:
                    from: validated
                    to:   prepatation_allowed
