framework:
    workflows:
        sutekinabox_publishing:
            type: 'workflow' # or 'state_machine'
            marking_store:
                type: 'single_state' # or 'multiple_state'
                arguments:
                    - 'state'
            supports:
                - App\Entity\SutekinaBox
                - App\SutekinaBox\SutekinaBoxRequest
            initial_place: created
            places:
                - created
                - to_validated
                - to_check_stock
                - to_purchase
                - prepatation_allowed
            transitions:
                to_validate:
                    from: created
                    to:   to_validated
                to_check:
                    from: to_validated
                    to:   to_check_stock
                to_purchase:
                    from: to_check_stock
                    to:   to_purchase
                to_be_prepared:
                    from: to_purchase
                    to:   prepatation_allowed
